export const API_ERRORS = {
  NO_TOKEN: "NO_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  DAILY_LIMIT_REACHED: "DAILY_LIMIT_REACHED",

  AI_QUOTA_EXCEEDED: "AI_QUOTA_EXCEEDED",
  AI_RATE_LIMIT: "AI_RATE_LIMIT",
  AI_FAILED: "AI_FAILED",

  SUPA_ERROR: "SUPA_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
};